
/* 
	Copyright 2021 Joseph Mason

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License. 
*/

let Glass_innerHTML = '<div class="glass-parent">'
	Glass_innerHTML += '<div class="glass-topline">'
	Glass_innerHTML +='	<div class="glass-top-logo"></div>'
	Glass_innerHTML +='	<div class="glass-top-buttons">'
	Glass_innerHTML +='		<svg data-value ="new"   viewBox="-5 -5 32 32" >'
	Glass_innerHTML +='			<rect x="3.5" y="1" rx="1" ry="1" width="15.5" height="20" style="  stroke-width: 1; fill:none;"/>'
	Glass_innerHTML +='			<text dominant-baseline="middle" text-anchor="middle" x="11" y="11"  fill="white" font-size="50%">+</text>'
	Glass_innerHTML +='		</svg>'
	Glass_innerHTML += '			<svg data-value="zoom-in"   viewBox="-5 -5 32 32" >'
	Glass_innerHTML += '				<circle class="glass-nofill" cx="8" cy="8" r="6" stroke="black" stroke-width="1" />'
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="8" y="8.5"  fill="black" font-size="50%" >+</text>'
	Glass_innerHTML += '				<path d="M11.8 11.8 L20 20" stroke="black" stroke-width="1">'
	Glass_innerHTML += '			</svg>'
	Glass_innerHTML += '			'
	Glass_innerHTML += '			<svg data-value="zoom-out"   viewBox="-5 -5 32 32" >'
	Glass_innerHTML += '				<circle class="glass-nofill" cx="8" cy="8" r="6" stroke="black" stroke-width="1"/>'
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="8" y="8" fill="black" font-size="50%" >-</text>'
	Glass_innerHTML += '				<path d="M11.8 11.8 L20 20" stroke="black" stroke-width="1">'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg data-value="undo"   viewBox="-5 -5 32 32" >'
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="11" fill="black" font-size="70%" >Undo</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg data-value="copy"   viewBox="-5 -5 32 32" title="copy">'
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="11" fill="black" font-size="70%" >Copy</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg data-value="paste"   viewBox="-5 -5 32 32" title="paste">'
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="11" fill="black" font-size="70%" >Paste</text>'
	Glass_innerHTML += '			</svg>'


	Glass_innerHTML += '			<svg data-value="import-export" viewBox="0 0 30 30" title="Import and Export Files">'
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="50%" y="50%" fill="black" font-size="70%" >I/O</text>'
	Glass_innerHTML += '			</svg>'	

	Glass_innerHTML += '			<svg class="glass_fullScreenModeSVG" data-value="fullScreenMode" viewBox="-5 -5 32 32">'
	Glass_innerHTML += '				<path d="M5 5 L5 16 L16 16 L16 5 Z" style="fill:none"/>'

	Glass_innerHTML += '				<path d="M5 5 L0 0" style="stroke-width: 1"/>'
	Glass_innerHTML += '				<path d="M2.5 2.5 L0 5 L0 0 L5 0 Z" />'

	Glass_innerHTML += '				<path d="M16 5 L21 0" style="stroke-width: 1"/>'
	Glass_innerHTML += '				<path d="M19 3 L21 5 L21 0 L16 0 Z" />'

	Glass_innerHTML += '				<path d="M16 16 L21 21" style="stroke-width: 1"/>'
	Glass_innerHTML += '				<path d="M18.5 18.5 L21 16 L21 21 L16 21 Z"/>'

	Glass_innerHTML += '				<path d="M5 16 L0 21" style="stroke-width: 1"/>'
	Glass_innerHTML += '				<path d="M3 19 L5 21 L0 21 L0 16 Z" />'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass_closefullScreenModeSVG" data-value="closeFullScreenMode" viewBox="-5 -5 32 32">'
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="12" y="11" fill="black" font-size="70%" >Close</text>'
	Glass_innerHTML += '			</svg>'


	Glass_innerHTML += '		</div>'
	Glass_innerHTML += '	</div>'
	Glass_innerHTML += '	<div class="glass-secondline">'
	Glass_innerHTML += '		<div class="glass-left-buttons">'

	Glass_innerHTML += '			<svg class="glass-left-buttons-1bond" data-value="1bond" height="30" width="30" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<path d="M2 2 L21 21"/>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-erase" data-value="erase" height="30" width="30" viewBox="-5 -5 32 32" >'
	Glass_innerHTML += '				<path d="M4 15 L4 20 L9 15 L9 10 Z"/>'
	Glass_innerHTML += '				<path d="M9 15 L9 10 L18 2 L18 7 Z" style="fill: none;" />'
	Glass_innerHTML += '				<path d="M0 20.5 L20 20.5" style="  stroke-width:1; fill: none;" />'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-atom" data-value="atom" height="22" width="22" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">C</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-pTable" data-value="pTable" height="22" width="22" viewBox="-5 -5 32 32" >'
	Glass_innerHTML += '				<path d="M1 5 L4 5 L4 15 L1 15 Z" />	'
	Glass_innerHTML += '				<path d="M4 8 L15 8 L15 15 L4 15 Z" />	'
	Glass_innerHTML += '				<path d="M21 15 L21 5 L15 5 L15 15 Z" />						'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-wedgebond" data-value="wedgebond" height="30" width="30" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<path d="M2 2 L20 16 L17 20 Z"/>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-hashbond" data-value="hashbond" height="30" width="30" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<path d="M3 2 L2 3" style="fill:black;" />'
	Glass_innerHTML += '				<path d="M7 5 L5 7" style="fill:black;" />'
	Glass_innerHTML += '				<path d="M11 8 L8 11" style="fill:black;" />'
	Glass_innerHTML += '				<path d="M15 11 L11 15" style="fill:black;" />'
	Glass_innerHTML += '				<path d="M19 14 L14 19" style="fill:black;" />'

	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-3ring" data-value="3"  viewBox="-5 -5 32 32"> '
	Glass_innerHTML += '				<path d="M11 1 L21 21 L1 21 Z"  style="  stroke-width: 1; fill:none;" />'
	Glass_innerHTML += '				<text x="7.5" y="18.5" font-size="smaller" fill="black">3</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-4ring" data-value="4" viewBox="-5 -5 32 32"> '
	Glass_innerHTML += '				<path d="M11 1 L21 11 L11 21 L1 11 Z" style="  stroke-width: 1; fill:none;" />'
	Glass_innerHTML += '				<text x="6.8" y="15.3" font-size="smaller" fill="black">4</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-5ring" data-value="5" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<path d="M11 1 L1 9 L5 21 L17 21 L21 9 Z" style="  stroke-width: 1; fill:none;" />'
	Glass_innerHTML += '				<text x="7.25" y="16.75" font-size="smaller" fill="black">5</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-6ring" data-value="6" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<path d="M16 2 L6 2 L1 11 L6 20 L16 20 L21 11 Z" style="  stroke-width: 1; fill:none;" />'
	Glass_innerHTML += '				<text x="7.5" y="15.5" font-size="smaller" fill="black">6</text>'
	Glass_innerHTML += '			</svg>'
	Glass_innerHTML += '			'
	Glass_innerHTML += '			<svg class="glass-left-buttons-benzene" data-value="benzene" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<path d="M16 2 L6 2 L1 11 L6 20 L16 20 L21 11 Z" style="  stroke-width: 1; fill:none;" />'
	Glass_innerHTML += '				<path d="M15 4 L7 4 M3 11 L7.25 18.5 M14.75 18.5 L19 11" style="  stroke-width:1; fill: none;" />'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-7ring" data-value="7" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<path d="M11 1 L3 5 L1 13 L7 20 L15 20 L21 13 L19 5 Z" style="  stroke-width: 1; fill:none;" />'
	Glass_innerHTML += '				<text x="7.5" y="15.5" font-size="smaller" fill="black">7</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-8ring" data-value="8" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<path d="M15 2 L7 2 L2 7 L2 15 L7 20 L15 20 L20 15 L20 7 Z" style="  stroke-width: 1; fill:none;" />'
	Glass_innerHTML += '				<text x="7.3" y="15.5" font-size="smaller" fill="black">8</text>'
	Glass_innerHTML += '			</svg>'
	Glass_innerHTML += '			'
	Glass_innerHTML += '			<svg class="glass-left-buttons-9ring" data-value="9" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<path d="M11 1 L5 3 L1 9 L2 16 L8 20 L14 20 L20 16 L21 9 L17 3 Z" style="  stroke-width: 1; fill:none;" />'
	Glass_innerHTML += '				<text x="7.6" y="15.5" font-size="smaller" fill="black">9</text>'
	Glass_innerHTML += '			</svg>'
	Glass_innerHTML += '			'
	Glass_innerHTML += '			<svg class="glass-left-buttons-nring" data-value="nring" viewBox="0 0 30 30" > '
	Glass_innerHTML += '				<circle class="glass-nofill" cx="14.5" cy="14.5" r="11" stroke="black" stroke-width="1" fill="none" />'
	Glass_innerHTML += '				<text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="black" font-size="smaller" >n</text>'
	Glass_innerHTML += '			</svg>'
	Glass_innerHTML += '			'
	Glass_innerHTML += '			<svg class="glass-left-buttons-arrow" data-value="arrow" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<path class="glass-nofill" d="M2 11 L19 11 L16 8 M19 11 L16 14" stroke="black" stroke-width="1"/>'
	Glass_innerHTML += '			</svg>'
	Glass_innerHTML += '			'
	Glass_innerHTML += '			<svg class="glass-left-buttons-positive" data-value="positive" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<circle class="glass-nofill" cx="11.5" cy="11.5" r="9" stroke="black" stroke-width="1" fill="none" />'
	Glass_innerHTML += '				<path d="M8 11.5 L15 11.5 M11.5 8 L11.5 15" stroke="black" stroke-width="1" />			'
	Glass_innerHTML += '			</svg>'
	Glass_innerHTML += '			'
	Glass_innerHTML += '			<svg class="glass-left-buttons-negative" data-value="negative" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<circle class="glass-nofill" cx="11.5" cy="11.5" r="9" stroke="black" stroke-width="1" fill="none" />'
	Glass_innerHTML += '				<path d="M8 11.5 L15 11.5" stroke="black" stroke-width="1"/>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '		</div>'
	Glass_innerHTML += '		<div class="glass-sketch-window"></div>'
	Glass_innerHTML += '	</div>'

	Glass_innerHTML += '	<div class="glass-popup glass-popup-import">'
	Glass_innerHTML += '		<div class="glass-popup-import-content">'
	Glass_innerHTML += '			<span>Paste molfile below: </span><br>'
	Glass_innerHTML += '			<textarea> </textarea>'
	Glass_innerHTML += '			<div class="glass-popup-button glass-importMol-button">Import Mol</div>'
	Glass_innerHTML += '		</div>'
	Glass_innerHTML += '	</div>'

	Glass_innerHTML += '	<div class="glass-popup glass-popup-export">'
	Glass_innerHTML += '		<div class="glass-popup-export-content">'
	Glass_innerHTML += '			<textarea> </textarea>'
	Glass_innerHTML += '			<div class="glass-popup-button">Close</div>'
	Glass_innerHTML += '		</div>'
	Glass_innerHTML += '	</div>'

	Glass_innerHTML += '	<div class="glass-popup glass-popup-atoms">'
	Glass_innerHTML += '		<div class="glass-popup-atoms-content">'
	Glass_innerHTML += '			<svg class="glass-left-buttons-carbon" data-value="C" height="22" width="22" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">C</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-hydrogen" data-value="H" height="22" width="22" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">H</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-oxygen" data-value="O" height="22" width="22" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">O</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-nitrogen" data-value="N" height="22" width="22" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">N</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-fluorine" data-value="F" height="22" width="22" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">F</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-chlorine" data-value="Cl" height="22" width="22" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Cl</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-bromine" data-value="Br" height="22" width="22" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Br</text>'
	Glass_innerHTML += '			</svg>'

	Glass_innerHTML += '			<svg class="glass-left-buttons-iodine" data-value="I" height="22" width="22" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '				<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">I</text>'
	Glass_innerHTML += '			</svg>'
	Glass_innerHTML += '		</div>'
	Glass_innerHTML += '	</div>'

	Glass_innerHTML += '	<div class="glass-popup glass-popup-pTable">'
	Glass_innerHTML += '		<div class="glass-popup-pTable-content">'
	Glass_innerHTML += '			<div class="glass-pTable-sBlock">'
	Glass_innerHTML += '				<svg class="glass-left-buttons-hydrogen" data-value="H" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">H</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<div class="break"></div>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-lithium" data-value="Li" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Li</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-beryllium" data-value="Be" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Be</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-sodium" data-value="Na" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Na</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-magnesium" data-value="Mg" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Mg</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-potassium" data-value="K" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">K</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-calcium" data-value="Ca" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ca</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-rubidium" data-value="Rb" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Rb</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-strontium" data-value="Sr" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Sr</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-cesium" data-value="Cs" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Cs</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-barium" data-value="Ba" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ba</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-francium" data-value="Fr" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Fr</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-radium" data-value="Ra" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ra</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '			</div>'
	Glass_innerHTML += '			'
	Glass_innerHTML += '			<div class="glass-pTable-dBlock">'
	Glass_innerHTML += '				<svg class="glass-left-buttons-scandium" data-value="Sc" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Sc</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-titanium" data-value="Ti" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ti</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-vanadium" data-value="V" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">V</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-chromium" data-value="Cr" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Cr</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-manganese" data-value="Mn" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Mn</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-iron" data-value="Fe" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Fe</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-cobalt" data-value="Co" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Co</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-nickel" data-value="Ni" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ni</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-copper" data-value="Cu" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Cu</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-zinc" data-value="Zn" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Zn</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<svg class="glass-left-buttons-yttrium" data-value="Y" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Y</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-zirconium" data-value="Zr" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Zr</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-niobium" data-value="Nb" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Nb</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-molybdenum" data-value="Mo" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Mo</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-technetium" data-value="Tc" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Tc</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-ruthenium" data-value="Ru" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ru</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-rhodium" data-value="Rh" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Rh</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-palladium" data-value="Pd" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Pd</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-silver" data-value="Ag" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ag</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-cadmium" data-value="Cd" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Cd</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<svg class="glass-left-buttons-lanthanum" data-value="La" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">La</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-hafnium" data-value="Hf" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Hf</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-tantalum" data-value="Ta" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ta</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-tungsten" data-value="W" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">W</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-rhenium" data-value="Re" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Re</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-osmium" data-value="Os" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Os</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-iridium" data-value="Ir" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ir</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-platinum" data-value="Pt" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Pt</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-gold" data-value="Au" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Au</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-mercury" data-value="Hg" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Hg</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<svg class="glass-left-buttons-actinium" data-value="Ac" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ac</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-rutherfordium" data-value="Rf" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Rf</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-dubnium" data-value="Db" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Db</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-seaborgium" data-value="Sg" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Sg</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-bohrium" data-value="Bh" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Bh</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-hassium" data-value="Hs" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Hs</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-meitnerium" data-value="Mt" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Mt</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-darmstadtium" data-value="Ds" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ds</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-roentgenium" data-value="Rg" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Rg</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-copernicum" data-value="Cn" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Cn</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '			</div>'
	Glass_innerHTML += '			'
	Glass_innerHTML += '			<div class="glass-pTable-pBlock">'
	Glass_innerHTML += '				<svg class="glass-left-buttons-helium" data-value="He" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">He</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<div class="break"></div>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<svg class="glass-left-buttons-boron" data-value="B" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">B</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-carbon" data-value="C" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">C</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-nitrogen" data-value="N" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">N</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-oxygen" data-value="O" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">O</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-fluorine" data-value="F" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">F</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-neon" data-value="Ne" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ne</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<svg class="glass-left-buttons-aluminium" data-value="Al" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Al</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-silicon" data-value="Si" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Si</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-phosphorus" data-value="P" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">P</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-sulfur" data-value="S" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">S</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-chlorine" data-value="Cl" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Cl</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-argon" data-value="Ar" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ar</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<svg class="glass-left-buttons-gallium" data-value="Ga" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ga</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-germanium" data-value="Ge" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ge</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-arsenic" data-value="As" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">As</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-selenium" data-value="Se" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Se</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-bromine" data-value="Br" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Br</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-krypton" data-value="Kr" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Kr</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<svg class="glass-left-buttons-indium" data-value="In" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">In</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-tin" data-value="Sn" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Sn</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-antimony" data-value="Sb" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Sb</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-tellurium" data-value="Te" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Te</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-iodine" data-value="I" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">I</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-xenon" data-value="Xe" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Xe</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<svg class="glass-left-buttons-thallium" data-value="Th" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Th</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-lead" data-value="Pb" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Pb</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-bismuth" data-value="Bi" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Bi</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-polonium" data-value="Po" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Po</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-astatine" data-value="As" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">As</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-radon" data-value="Rn" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Rn</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<svg class="glass-left-buttons-nihonium" data-value="Nh" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Nh</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-flerovium" data-value="Fl" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Fl</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-moscovium" data-value="Mc" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Mc</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-livermorium" data-value="Lv" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Lv</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-tennessine" data-value="Ts" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ts</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-oganesson" data-value="Og" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Og</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '			</div>'
	Glass_innerHTML += '			'
	Glass_innerHTML += '			<div class="break" style="height: 10px;"></div>'
	Glass_innerHTML += '			'
	Glass_innerHTML += '			<div class="glass-pTable-fBlock">'
	Glass_innerHTML += '				<svg class="glass-left-buttons-cerium" data-value="Ce" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ce</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-praseodymium" data-value="Pr" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Pr</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-neodymium" data-value="Nd" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Nd</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-promethium" data-value="Pm" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Pm</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-samarium" data-value="Sm" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Sm</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-europium" data-value="Eu" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Eu</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-gadolinium" data-value="Gd" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Gd</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-terbium" data-value="Tb" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Tb</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-dysprosium" data-value="Dy" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Dy</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-holmium" data-value="Ho" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Ho</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-erbium" data-value="Er" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Er</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-thulium" data-value="Tm" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Tm</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-ytterbium" data-value="Yb" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Yb</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-lutetium" data-value="Lu" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Lu</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				'
	Glass_innerHTML += '				<svg class="glass-left-buttons-thorium" data-value="Th" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Th</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-protactinium" data-value="Pa" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Pa</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-uranium" data-value="U" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">U</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-neptunium" data-value="Np" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Np</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-plutonium" data-value="Pu" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Pu</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-americium" data-value="Am" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Am</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-curium" data-value="Cm" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Cm</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-berkelium" data-value="Bk" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Bk</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-californium" data-value="Cf" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Cf</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-einsteinium" data-value="Es" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Es</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-fermium" data-value="Fm" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Fm</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-mendelevium" data-value="Md" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Md</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-nobelium" data-value="No" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">No</text>'
	Glass_innerHTML += '				</svg>'
	Glass_innerHTML += '				<svg class="glass-left-buttons-lawrencium" data-value="Lr" viewBox="-5 -5 32 32" > '
	Glass_innerHTML += '					<text dominant-baseline="middle" text-anchor="middle" x="11" y="13" font-size="larger" fill="black">Lr</text>'
	Glass_innerHTML += '				</svg>'
		
	Glass_innerHTML += '			</div>'
	Glass_innerHTML += '		</div>'
	Glass_innerHTML += '	</div>'
		
	Glass_innerHTML += '	<div class="glass-popup glass-popup-nring">'
	Glass_innerHTML += '		<div class="glass-popup-nring-content">'
	Glass_innerHTML += '			<input type="number" placeholder="Size of ring" min="3" value="3"></input>'
	Glass_innerHTML += '			<div class="glass-button glass-nring-button">Add Ring</div>'
	Glass_innerHTML += '		</div>'
	Glass_innerHTML += '	</div>'

	Glass_innerHTML += '	<div class="glass-popup glass-popup-importexport">'
	Glass_innerHTML += '		<div class="glass-popup-importexport-content">'
	Glass_innerHTML += '			<div class="glass-popup-IE-header">'
	Glass_innerHTML += '				<input type="button" class="glass-button glass-button-IE glass-IE-header-import highlight-svg" value="Import"></input> '
	Glass_innerHTML += '				<input type="button" class="glass-button glass-button-IE glass-IE-header-export" value="Export"></input> '
	Glass_innerHTML += '			</div>'

	Glass_innerHTML += '			<div class="glass-popup-IE-import">'
	Glass_innerHTML += '				<p>Enter MOL text or Glass here:</p>'
	Glass_innerHTML += '				<textarea class="glass-textarea glass-import-textarea glass-IE-import"></textarea>'
	Glass_innerHTML += '				<input type="button" class="glass-button glass-button-IE glass-import-button" value="Import"></input>'
	Glass_innerHTML += '			</div>'
	Glass_innerHTML += '			<div class="glass-popup-IE-export" style="display: none;">'
	Glass_innerHTML += '				<input type="button" class="glass-button glass-button-IE glass-export-toGlass" value="Glass"></input> '
	Glass_innerHTML += '				<input type="button" class="glass-button glass-button-IE glass-export-toMol" value="Mol2000"></input> '
	Glass_innerHTML += '				<input type="button" class="glass-button glass-button-IE glass-export-toSmiles" value="SMILES"></input> '
	Glass_innerHTML += '				<textarea class="glass-textarea glass-export-textarea"></textarea>'
	Glass_innerHTML += '			</div>'
	Glass_innerHTML += '		</div>'
	Glass_innerHTML += '	</div>'


	Glass_innerHTML += '</div>'
